# Generated by Django 5.0.6 on 2026-07-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('icon', models.CharField(default='Document', max_length=50, verbose_name='图标名称(Element Plus)')),
                ('category', models.CharField(choices=[('iqair', 'IQAir及竞品数据面板'), ('air_quality', '空气质量实时监测面板'), ('sales', '销售数据分析面板'), ('weekly', '周报面板'), ('daily', '日报面板')], default='iqair', max_length=20, verbose_name='项目分类')),
                ('route', models.CharField(max_length=200, verbose_name='前端路由地址')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='project_thumbnails/', verbose_name='缩略图')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'projects',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
