# Generated by Django 5.0.6 on 2026-07-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gradient_color',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='渐变色 CSS 值'),
        ),
        migrations.AddField(
            model_name='project',
            name='icon_type',
            field=models.CharField(choices=[('image', '图片'), ('emoji', 'Emoji'), ('icon_name', '图标名称(Element Plus)')], default='icon_name', max_length=20, verbose_name='图标类型'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='首页展示(色块)'),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='副标题/简介'),
        ),
    ]
