# Generated by Django 5.0.6 on 2026-07-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_add_icon_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='gradient_color',
            field=models.CharField(blank=True, default='', help_text='CSS linear-gradient 值，例如: linear-gradient(135deg, #4F46E5, #7C3AED)', max_length=200, verbose_name='渐变色'),
        ),
    ]
