services:
  backend:
    volumes:
      - ./backend:/app/backend
    command: >
      sh -c "mkdir -p /app/logs &&
             python manage.py migrate &&
             python manage.py init_admin &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2 --reload"

  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 8888"

networks:
  iqair-network:
    driver: bridge