services:
  backend:
    volumes:
      - ./uploadfiles:/app/uploadfiles
    command: >
      sh -c "mkdir -p /app/logs &&
             python manage.py migrate &&
             python manage.py init_admin &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 120 --access-logfile /app/logs/gunicorn_access.log --error-logfile /app/logs/gunicorn_error.log"

  celery-worker:
    command: sh -c "mkdir -p /app/logs && celery -A config worker -l info --concurrency=4"

  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - "8888:80"

networks:
  iqair-network:
    driver: bridge