# Generated by Django 5.0.6 on 2026-07-11 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='网站名称')),
                ('url', models.CharField(max_length=500, verbose_name='链接地址')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='link_icons/', verbose_name='图标图片')),
                ('icon_emoji', models.CharField(blank=True, default='', max_length=20, verbose_name='图标Emoji(备选)')),
                ('category', models.CharField(choices=[('work_sites', '工作站点'), ('personal_sites', '个人站点'), ('tools', '实用工具'), ('ai_tools', 'AI工具')], default='work_sites', max_length=20, verbose_name='分类')),
                ('is_internal', models.BooleanField(default=False, verbose_name='是否内部链接(使用路由跳转)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网站链接',
                'verbose_name_plural': '网站链接',
                'db_table': 'website_links',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('website_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='navigation.websitelink', verbose_name='网站链接')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
                'db_table': 'user_favorites',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'website_link')},
            },
        ),
    ]
