# Generated by Django 5.0.6 on 2026-07-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_restore_userfavorite_and_seed_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitelink',
            name='icon_fetch_failed',
            field=models.BooleanField(default=False, verbose_name='图标抓取失败'),
        ),
        migrations.AlterField(
            model_name='websitelink',
            name='category',
            field=models.CharField(choices=[('work_sites', '工作站点'), ('personal_sites', '个人站点'), ('tools', '实用工具'), ('ai_tools', 'AI工具'), ('common_sites', '常用网址'), ('friend_links', '友情链接'), ('ai_resources', 'AI工具资料')], default='work_sites', max_length=20, verbose_name='分类'),
        ),
        migrations.AddIndex(
            model_name='websitelink',
            index=models.Index(fields=['category', 'sort_order'], name='wlink_cat_sort_idx'),
        ),
    ]
