# Generated by Django 5.0.6 on 2026-07-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_restore_userfavorite_and_seed_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitelink',
            name='category',
            field=models.CharField(choices=[('common_sites', '常用网址'), ('friend_links', '友情链接'), ('ai_resources', 'AI工具资料'), ('work_sites', '工作站点'), ('personal_sites', '个人站点'), ('tools', '实用工具'), ('ai_tools', 'AI工具')], default='work_sites', max_length=20, verbose_name='分类'),
        ),
    ]
