# Generated by Django 5.0.6 on 2026-07-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_alter_websitelink_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitelink',
            name='icon_fetch_failed',
            field=models.BooleanField(default=False, verbose_name='图标抓取失败'),
        ),
    ]
