# Generated by Django 5.0.6 on 2026-07-10 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品牌名称')),
                ('color', models.CharField(default='#64748B', max_length=20, verbose_name='图表颜色')),
                ('logo', models.TextField(blank=True, default='', verbose_name='Logo (base64 或 URL)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'db_table': 'brands',
                'ordering': ['sort_order', '-created_at'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FilterRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20, verbose_name='期间 (如 2024 H1)')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='销售额 (元)')),
                ('filter_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='滤芯占比 (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='dashboard.brand', verbose_name='品牌')),
            ],
            options={
                'verbose_name': '滤芯营收数据',
                'verbose_name_plural': '滤芯营收数据',
                'db_table': 'filter_revenues',
                'ordering': ['period', '-revenue'],
                'unique_together': {('brand', 'period')},
            },
        ),
    ]
