# Generated by Django 5.0.6 on 2026-07-25 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_uitext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='filterrevenue',
            index=models.Index(fields=['brand', 'period'], name='filterrev_brand_period_idx'),
        ),
        migrations.AddIndex(
            model_name='platformsalesdata',
            index=models.Index(fields=['platform', 'period_type', 'date'], name='psd_pltfm_period_date_idx'),
        ),
    ]
