# Generated by Django 5.0.6 on 2026-07-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_refactor_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn_text', models.CharField(max_length=50, verbose_name='中文关键词')),
                ('en_text', models.CharField(blank=True, default='', max_length=50, verbose_name='英文关键词')),
                ('weight', models.IntegerField(default=50, verbose_name='权重(1-100)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '词云关键词',
                'verbose_name_plural': '词云关键词',
                'db_table': 'cloud_words',
                'ordering': ['-weight'],
            },
        ),
    ]
