# Generated by Django 5.0.6 on 2026-07-25 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['user', 'timestamp'], name='oplog_user_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['module', 'timestamp'], name='oplog_module_ts_idx'),
        ),
    ]
