# Generated by Django 5.0.6 on 2026-07-10 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('small_data', models.JSONField(blank=True, null=True, verbose_name='小数据 (JSON)')),
                ('file_path', models.CharField(blank=True, default='', max_length=500, verbose_name='大数据文件路径')),
                ('is_large', models.BooleanField(default=False, verbose_name='是否为大数据文件')),
                ('operation_type', models.CharField(choices=[('create', '新增'), ('update', '修改'), ('delete', '删除'), ('login', '登录'), ('logout', '登出'), ('restore', '撤销恢复')], default='update', max_length=20, verbose_name='操作类型')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注说明')),
                ('is_manual', models.BooleanField(default=False, verbose_name='是否手动创建')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='projects.project', verbose_name='项目')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '数据快照',
                'verbose_name_plural': '数据快照',
                'db_table': 'data_snapshots',
                'ordering': ['-timestamp'],
            },
        ),
    ]
