# Generated by Django 5.0.6 on 2026-07-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dataease_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DataEase密码哈希(BCrypt)'),
        ),
    ]
